---
title: "databehandling"
author: "Søren D. NIelsen"
date: "1 maj 2019"
output: html_document
---

```{r setup, include=FALSE}
library(RandomFields)
#library(kriging)
#library(sp)
#library(gstat)
#library(dplyr)
#library(ggplot2)
#library(scales)
#library(magrittr)
```


```{r}
Aalborg <- read.csv("Aalborg.csv")
#str(Aalborg)
```

```{r}
Aalborg <- subset(Aalborg, ykoor!=min(ykoor))
```


```{r}

Aalborg2 <- RFspatialPointsDataFrame(coords = Aalborg[, c("xkoor","ykoor")], data = Aalborg[, c("Kontantpris","Kontantpris")], RFparams = list(vdim=1, n=2) )
```

```{r}
dta <- Aalborg2["Kontantpris"]
```

```{r}
plot(Aalborg2, zlim=cbind(c(200000,8*10^6)))
```

```{r}
model2 <- RMgauss(var=NA) +RMtrend(mean = NA)
modfit <- RFfit(model2, data = Aalborg2)
modfit
```

```{r}
x <- seq(0, 4, 0.05)
z <- RFinterpolate(model = model2, x=x, y=x, data=Aalborg2)
```
















måske ikke bruge alligevel
```{r}
#A <- matrix(c(Aalborg2$xkoor,Aalborg2$ykoor), nrow=5651)
#y <- conventional2RFspDataFrame(Aalborg2, coords =A )
```

```{r}
minx <- min(Aalborg$xkoor)
miny <- min(Aalborg$ykoor)
numbx <- ceiling(max(Aalborg$xkoor)-minx)
numby <- ceiling(max(Aalborg$ykoor)-miny)
y <- GridTopology(c(minx,miny),c(1,1),c(numbx,numby))
```

```{r}
#Aa <- Aalborg[duplicated(xkoor,ykoor, .keep_all = TRUE)]
```


```{r}
#Aalborg2 <- Aalborg %>% distinct(xkoor,ykoor, .keep_all = TRUE)
```


```{r}
coordinates(Aalborg) <- ~xkoor+ykoor+Salgsdato
Aalborg2 <- sp2RF(Aalborg, param = list(n=1, vdim=50))
Dta <- cbind(Aalborg[,50:51])
```


```{r}
data1 <- Aalborg[,12]
pris <- log(Aalborg$Kontantpris)
model <- pris ~ 1
<<<<<<< HEAD
model2 <- RMgengneiting()
c <- RFfit(model, data= Aalborg2, allowdistanceZero=TRUE)
=======
c <- RFfit(model=model, x=Dta , data= data1, allowdistanceZero=TRUE)
>>>>>>> b14aa0caeab4c6195ab9e7ac393266f035168ef6
```

```{r}
dist.mat <- as.vector(RFearth2cartesian(Aalborg[,52:53]))
```
```{r}
P <- Aalborg[,12]
model <- RMgauss()+RMtrend(mean = NA)
Pmodel <- RFfit(model = model, distances = dist.mat, dim = 3, data = P)
```



<<<<<<< HEAD

```{r}
points <-1000 
x <- runif(points, 0, 3)
y <- runif(points, 0, 3) ## random points in square [0, 3]^2
model <- RMgencauchy(alpha=1, beta=2)
d <- RFsimulate(model, x=x, y=y, grid=FALSE, n=1000)
```
```{r}
estmodel <- RMgencauchy(var=NA, scale=NA, alpha=NA, beta=2) +
            RMtrend(mean=NA)
RFfit(estmodel, data=d)
```
```{r}
plot(Aalborg)
```

```{r}
plotRF(Aalborg2)
```
```{r}
plot(d)
```
```{r}
Model <- likfit(s100,ini=c(0.5,0.5), fix.nug=TRUE)
```
```{r}
Model
```
```{r}
summary(Model)
```
```{r}
reml <- likfit(s100,ini=c(0.5,0.5),fix.nug=TRUE, lik.met="REML")
```
```{r}
summary(reml)
```
```{r}
plot(variog(s100))
lines(Model)
lines(reml, lty=2)
```
```{r}
Aalborg <- as.numeric(Aalborg)
```
```{r}
ml <- likfit(y, ini=c(0.5, 0.5), fix.nug = TRUE)
```

```{r}
Aalborgv <- as.vector(Aalborg[,12])
```
```{r}
model1 <- likfit(Aalborgv, ini=c(0.5,0,5, fix.nug=TRUE))
```

```{r}
v <- s100
```
```{r}
plot(Aalborg)
```

=======
>>>>>>> b14aa0caeab4c6195ab9e7ac393266f035168ef6
