---
title: "noget andet"
author: "Søren D. NIelsen"
date: "9 maj 2019"
output: html_document
---

```{r setup, include=FALSE}
library(RandomFields)
library(kriging)
library(sp)
library(gstat)
library(dplyr)
library(ggplot2)
library(scales)
library(magrittr)
library(spatstat)
library(colorspace)
library(RColorBrewer)
library(mvtnorm)
library(raster)
library(tcltk2)
library(tkrplot)
library(spam)
library(tools)
library(geoR)
library(minqa)
library(soma)
library(optimx)
library(nloptr)
library(pso)
library(GenSA)
```

```{r}
RFoptions(seed=0) ## *ANY* simulation will have the random seed 0; set
##                   RFoptions(seed=NA) to make them all random again




RFoptions(modus_operandi="normal")
```

```{r}
## Preparation of graphics
dev.new(height=7, width=16)
## creating random variables first
## here, a grid is chosen, but does not matter
p <- 3:8
points <- as.matrix(expand.grid(p,p))
model <- RMexp() + RMtrend(mean=1)
dta <- RFsimulate(model, x=points)
x <- seq(2, 10, 0.15)
```

```{r}
model <- RMexp() + RMtrend(mean=NA)
z <- RFinterpolate(model, x=x, y=x, data=dta)
plot(z,dta)

```



```{r}
points <- 100
x <- runif(points, 0, 3)
y <- runif(points, 0, 3) ## random points in square [0, 3]^2
model <- RMgencauchy(alpha=1, beta=2)
d <- RFsimulate(model, x=x, y=y, grid=FALSE, n=1) #1000
```

```{r}
dev.new(height=50, width=50)
p <- 1:10
points <- as.matrix(expand.grid(p,p))
model45 <- RMgauss() + RMtrend(mean=1)
dta <- RFsimulate(model45, x=points)
plot(dta)
x <- seq(0, 11, 0.25)

```

simple
```{r}
model <- RMgauss() + RMtrend(mean=1)
z <- RFinterpolate(model, x=x, y=x, data=dta)
plot(z, dta)
```


ordinær kriging
```{r}
model <- RMgauss() + RMtrend(mean=NA)
z <- RFinterpolate(model, x=x, y=x, data=dta)
plot(z, dta)
```

```{r}
points <- 100
x <- runif(points, 0, 3)
y <- runif(points, 0, 3) ## random points in square [0, 3]^2
model <- RMgauss(var=0.8, scale = 0.5)+RMtrend(mean=4)
d <- RFsimulate(model, x=x, y=y, grid=FALSE, n=10) #1000
plot(d)
```

```{r}
model2 <- RMgauss(var=NA, scale = NA) +RMtrend(mean = NA)
modfit <- RFfit(model2, data = d)
modfit
```

```{r}
model3 <- RMexp(var=NA, scale = NA) +RMtrend(mean = NA)
modfit2 <- RFfit(model3, data = d)
modfit2
```


```{r}
x <- seq(0, 4, 0.05)
z <- RFinterpolate(model = modfit, x=x, y=x, data=d)
plot(z)
```

```{r}
cr <- RFcrossvalidate(model2, data = d)
```



















```{r}
var2 <- RFvariogram(data=d) 
plot(var2)
```

```{r}
model <- RMexp()
x <- seq(0, 10, 0.02)
z <- RFsimulate(model, x=x, n=2)
emp.vario <- RFvariogram(data=z)
plot(emp.vario, model=model)

```


```{r}
#estmodel <- RMgencauchy(var=NA, scale=NA, alpha=NA, beta=2) +
#            RMtrend(mean=NA)
#gh <- RFfit(estmodel, data=d)
```




```{r}
#A=as.data.frame(cbind(Aalborg$Kontantpris,Aalborg$xkoor,Aalborg$ykoor))
#Asub <- A[sample(1000,size = 50),]
#coordinates(Asub) <- ~V2+V3
#Asub <- sp2RF(Asub, param = list(n=1, vdim=1))
#A2sub <- 
```

```{r}
data("weather")
```

```{r}
dist.mat <- as.vector(RFearth2cartesian(weather[,3:4]))
```

```{r}
nug <- RMmatrix(M = matrix(nc = 2, c(NA, 0, 0, NA)), RMnugget())
pars.model <- nug + RMbiwm(nudiag = c(NA, NA), scale = NA, cdiag = c(NA, NA), rhored = NA)

```



```{r}
P <- weather[,1:2]
pars <- RFfit(model = pars.model, distances = dist.mat, dim = 1, data = P)
```


```{r}
a <- colMeans(weather[, 3:4]) * pi / 180
P <- cbind(c(-sin(a[1]), cos(a[1]), 0), c(-cos(a[1]) * sin(a[2]), -sin(a[1]) * sin(a[2]), cos(a[2])), c(cos(a[1]) * cos(a[2]), sin(a[1]) * cos(a[2]), sin(a[2])))
x <- RFearth2cartesian(weather[, 3:4])
plane <- (x %*% P)[, 1:2]

```

```{r}
n <- 200
r <- apply(plane, 2, range)
data <- cbind(plane, weather[, 1:2])
z <- RFinterpolate(pars, data = data, dim = 2, x = seq(r[1, 1], r[2, 1], length = n), y = seq(r[1, 2], r[2, 2], length = n), varunits = c("Pa", "K"))
plot(z)

```






































