---
title: "Test"
output: html_document
---





```{r}
dta <- Aalborg["Kontantpris"]
```
```{r}
Aalborg <- read.csv("Aalborg.csv")
str(Aalborg)
Aalborg <-RFspatialPointsDataFrame(
 coords = Aalborg[,c("xkoor", "ykoor")],
 data = Aalborg[,c("Kontantpris","")],
 RFparams=list(vdim=1, n=1)) 
```
```{r}
Pris <- Aalborg["data"]
```

```{r}
Model <-~1+RMwhittle(scale=NA, var=NA, nu=NA) + RMnugget(var=NA)
```
```{r}
fit <- RFfit(Model,data=Pris,allowdistanceZero=TRUE)
```

```{r}
x <- as.vector(Aalborg["xkoor"])
y <- as.vector(Aalborg["ykoor"])
```
```{r}
?ppp
```

```{r}
max(x)
min(x)
```

```{r}
max(y)
min(y)
```

```{r}
a <- as.numeric(unlist(x))
b <- as.numeric(unlist(y))
```

```{r}
xt <- as.vector(c(520000,585000))
yt <- as.vector(c(6200000,6350000))
```


```{r}
O <- owin(xt,yt)
```


```{r}
HuspriserAA <- ppp(a,b, O)
HuspriserAAny <- unique.ppp(HuspriserAA)
```

```{r}
plot(HuspriserAAny)
```
```{r}
DensAA <- density(HuspriserAAny)
plot(DensAA)
```
```{r}
K <- Kest(HuspriserAAny)
plot(K)
```
```{r}
plot(K, sqrt(iso/pi) ~ r)
 plot(K, sqrt(./pi) ~ r, ylab="L(r)", main="L function for cells")
```
```{r}
Env <- envelope(HuspriserAAny, fun=Kest)
```

```{r}
plot(Env)
```

```{r}

```

